# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Artificien' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Artificien
  pod 'OpenMinedSwiftSyft', '~> 0.1.3-beta1'

end
